language: node_js

addons:
  apt:
    packages:
      - tree


before_install:
  - npm install -g bower gulp
  - apt-get install tree

install:
  - npm install
  - bower install
script:
  - gulp --gulpfile test-gulpfile.js
  - tree public
