language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
addons:
  apt:
    packages:
      - tree


before_install:
  - npm install -g bower gulp

install:
  - npm install
  - bower install
script:
  - npm test
  - tree public
